[package]
name = "msvc-env"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
tempfile = "3.8"
thiserror = "1.0"

[dev-dependencies]
serial_test = "2.0"
